// Tealium View Event Templates using centralized patterns
// This file contains all TealiumView specifications built from pattern references
// Requires patterns.js to be loaded first

window.expectedTealiumViewObjects = [
  {
    event: "TealiumView",
    currency: "@PATTERNS.currency",
    funnel_name: "Trains",
    page_category: "SearchResults",
    isLoggedIn: "@PATTERNS.boolean",
    customer_hashedemail: "@PATTERNS.hashedEmail",
    membershipID: "@PATTERNS.membershipId",
    loyaltyTier: "@PATTERNS.loyaltyTier",
    pointsToSpend: "@PATTERNS.number",
    pointsToUpgrade: "@PATTERNS.numberOptional",
    customer_is_admin: "@PATTERNS.booleanOptional",
    businessID: "@PATTERNS.businessId",
    subscriptionDuration: "@PATTERNS.numberOptional",
    subscriptionRemainingDuration: "@PATTERNS.numberOptional",
    pointsOrRegular: "@PATTERNS.bookingType",
    numberOfResults: "@PATTERNS.number",
    numberOfTrainsAvailable: "@PATTERNS.number",
    sOutboundLowestFare: "@PATTERNS.numberOptional",
    sInboundLowestFare: "@PATTERNS.numberOptional",
    numberOfSalesTagsAvailable: "@PATTERNS.number",
    directOrConnection: "@PATTERNS.connectionType",
    sJourneyType: "@PATTERNS.journeyType",
    sFromCode: "@PATTERNS.stationCode",
    sFromName: "@PATTERNS.requiredText",
    sToCode: "@PATTERNS.stationCode",
    sToName: "@PATTERNS.requiredText",
    sDateOutbound: "@PATTERNS.date",
    sDateInbound: "@PATTERNS.dateOptional",
    sTravelDuration: "@PATTERNS.numberOptional",
    sTravelHorizon: "@PATTERNS.number",
    sPaxAdult: "@PATTERNS.number",
    sPaxChildren: "@PATTERNS.number",
    sPaxYouth: "@PATTERNS.number",
    sPaxInfants: "@PATTERNS.number",
    sPaxSenior: "@PATTERNS.number",
    sPaxCompanion: "@PATTERNS.companionCount",
    sPaxTotal: "@PATTERNS.number",
    basket_value: "@PATTERNS.number",
    basket_value_inpoints: "@PATTERNS.number",
    ecommerce_action: "product impressions",
    products_count: "@PATTERNS.number",
    product_name: [/^\d{7} - \d{7}(:adult)?$/], // as array
    product_id: [/^\d{7} - \d{7}$/],
    product_quantity: ["@PATTERNS.number"],
    product_status: ["@PATTERNS.productStatus"],
    product_price: ["@PATTERNS.priceDecimal"],
    product_price_inpoints: ["@PATTERNS.numberOptionalExtended"],
    product_brand: ["@PATTERNS.trainBrand"], // e.g., ES, ER
    product_category: ["trains"],
    product_variant: ["@PATTERNS.productVariant"],
    product_departure_date: ["@PATTERNS.date"],
    product_return_date: ["@PATTERNS.dateOptional"],
    product_train_class: ["@PATTERNS.trainClass"],
    product_train_route: ["@PATTERNS.trainRoute"],
    product_train_origin_stationcode: ["@PATTERNS.stationCode"],
    product_train_destination_stationcode: ["@PATTERNS.stationCode"],
    product_train_number: ["@PATTERNS.trainNumber"],
    product_train_fbccode: ["@PATTERNS.anyText"], // some may be null
    product_train_departuretime: ["@PATTERNS.time"],
    product_train_arrivaltime: ["@PATTERNS.time"],
    product_train_numberofconnections: ["@PATTERNS.number"],
    product_train_connectionoperator: ["@PATTERNS.connectionOperator"],
    product_train_tickettype: ["@PATTERNS.trainTicketType"],
    product_train_passenger_type: ["@PATTERNS.passengerType"],
    product_train_sale_tag: ["@PATTERNS.saleTag"],
    product_travel_date: ["@PATTERNS.date"],
    product_train_fare_name: ["@PATTERNS.fareName"],
    product_train_fare_type: ["@PATTERNS.fareType"], 
    product_total_journey_length: ["@PATTERNS.number"],
    product_train_journey_length: ["@PATTERNS.number"],
    page_name: /^(Upgrade\/)?SearchResults(\/Inbound)?$/
  },
	// FLEXIDATE SRP
	  {
    event: "TealiumView",
    currency: "@PATTERNS.currency",
    funnel_name: "Trains",
    page_category: /^SearchResults$/, // strict category
    isLoggedIn: "@PATTERNS.boolean",
    customer_hashedemail: "@PATTERNS.hashedEmail",
    membershipID: "@PATTERNS.membershipId",
    loyaltyTier: "@PATTERNS.loyaltyTier",
    pointsToSpend: "@PATTERNS.number",
    pointsToUpgrade: "@PATTERNS.numberOptional",
    customer_is_admin: "@PATTERNS.booleanOptional",
    businessID: "@PATTERNS.businessId",
    subscriptionDuration: "@PATTERNS.numberOptional",
    subscriptionRemainingDuration: "@PATTERNS.numberOptional",
    pointsOrRegular: "@PATTERNS.bookingType",
    numberOfResults: "@PATTERNS.number",
    numberOfTrainsAvailable: "@PATTERNS.number",
    sOutboundLowestFare: "@PATTERNS.numberOptional",
    sInboundLowestFare: "@PATTERNS.numberOptional",
    numberOfSalesTagsAvailable: null,
    directOrConnection: "@PATTERNS.connectionType",
    sJourneyType: "@PATTERNS.journeyType",
    sFromCode: "@PATTERNS.stationCode",
    sFromName: "@PATTERNS.requiredText",
    sToCode: "@PATTERNS.stationCode",
    sToName: "@PATTERNS.requiredText",
    sDateOutbound: null,
    sDateInbound: null,
    sTravelDuration: null,
    sTravelHorizon: null,
    sPaxAdult: "@PATTERNS.number",
    sPaxChildren: "@PATTERNS.number",
    sPaxYouth: "@PATTERNS.number",
    sPaxInfants: "@PATTERNS.number",
    sPaxSenior: "@PATTERNS.number",
    sPaxCompanion: "@PATTERNS.companionCount",
    sPaxTotal: "@PATTERNS.number",
    basket_value: "@PATTERNS.number",
    basket_value_inpoints: "@PATTERNS.number",
    ecommerce_action: "product impressions",
    products_count: "@PATTERNS.number",
    product_name: [/^\d{7} - \d{7}(:adult)?$/], // as array
    product_id: [/^\d{7} - \d{7}$/],
    product_quantity: ["@PATTERNS.number"],
    product_status: ["@PATTERNS.productStatus"],
    product_price: ["@PATTERNS.priceDecimal"],
    product_price_inpoints: ["@PATTERNS.numberOptionalExtended"],
    product_brand: ["@PATTERNS.trainBrand"], 
    product_category: ["trains"],
    product_variant: ["@PATTERNS.productVariant"],
    product_departure_date: [/^\d{4}-\d{2}-\d{2}|null$/],
    product_return_date: ["@PATTERNS.dateOptional"],
    product_train_class: ["@PATTERNS.trainClass"],
    product_train_route: ["@PATTERNS.trainRoute"],
    product_train_origin_stationcode: ["@PATTERNS.stationCode"],
    product_train_destination_stationcode: ["@PATTERNS.stationCode"],
    product_train_number: ["@PATTERNS.trainNumber"],
    product_train_fbccode: ["@PATTERNS.anyText"], // some may be null
    product_train_departuretime: ["@PATTERNS.time"],
    product_train_arrivaltime: ["@PATTERNS.time"],
    product_train_numberofconnections: ["@PATTERNS.number"],
    product_train_connectionoperator: ["@PATTERNS.connectionOperator"],
    product_train_tickettype: ["@PATTERNS.trainTicketTypeExtended"], // some may be null
    product_train_passenger_type: ["@PATTERNS.passengerType"],
    product_train_sale_tag: ["@PATTERNS.saleTag"],
    product_travel_date: ["@PATTERNS.date"],
    product_train_fare_name: ["@PATTERNS.fareName"],
    product_train_fare_type: ["@PATTERNS.fareType"], 
    product_total_journey_length: ["@PATTERNS.number"],
    product_train_journey_length: ["@PATTERNS.number"],
    page_name: "SearchResults/FlexiDates"
  },
{
    event: "TealiumView",
    app_name: "ManageBooking",
    app_platform: "ReactJS",
    currency: "@PATTERNS.currency",
    language: "@PATTERNS.language",
	market: "@PATTERNS.market",
    page_category: "Exchange",
    isLoggedIn: "true",
    customer_hashedemail: "@PATTERNS.hashedEmail",
    membershipID: /^\d{17}|null$/,
    loyaltyTier: "@PATTERNS.loyaltyTier",
    businessID: "@PATTERNS.businessId",
    customer_is_admin: "false",
    sFromCode: "@PATTERNS.stationCode",
    sFromName: "@PATTERNS.requiredText",
    sToCode: "@PATTERNS.stationCode",
    sToName: "@PATTERNS.requiredText",
    sJourneyType: "@PATTERNS.journeyType",
    activityType: "train exchange",
    pointsOrRegular: "@PATTERNS.bookingType",
    sDateOutbound: "@PATTERNS.date",
    sDateInbound: "@PATTERNS.dateOptional",
    sTravelDuration: "@PATTERNS.numberOptional",
    sTravelHorizon: "@PATTERNS.number",
    sPaxAdult: "@PATTERNS.number",
    sPaxChildren: "@PATTERNS.number",
    sPaxYouth: "@PATTERNS.number",
    sPaxInfants: "@PATTERNS.number",
    sPaxSenior: "@PATTERNS.number",
    sPaxCompanion: "@PATTERNS.number",
    sPaxTotal: "@PATTERNS.number",
    sInTrains: "@PATTERNS.anyText",
    sInTrainsAv: "@PATTERNS.number",
    sTrainList: ["@PATTERNS.anyText"],
    basket_value: "@PATTERNS.number",
    basket_value_inpoints: "@PATTERNS.number",
    priceAdultOutbound: "@PATTERNS.number",
    priceChildOutbound: "@PATTERNS.number",
    priceSeniorOutbound: "@PATTERNS.number",
    priceYouthOutbound: "@PATTERNS.number",
    sClassOutbound: "@PATTERNS.trainClass",
    sOutboundTime: "@PATTERNS.time",
    sOutboundArrivalTime: "@PATTERNS.time",
    sOutboundConnectionCode: [/^(null|\d{7})$/],
    sOutboundConnectionOperator: ["@PATTERNS.connectionOperator"],
    sTrainNumberOutbound: "@PATTERNS.trainNumber",
    sTrainTarriffOutbound: /^[A-Z0-9]{11}$/,
    sTrainTypeOutbound: "@PATTERNS.trainTicketType",
    directOrConnection: "@PATTERNS.connectionType",
    page_name: /^Exchange\/SearchResults(\/Inbound)?$/
  },
{
	event: "TealiumView",
	ecommerce_action: "product impressions",
	app_name: /^(Packages|Hotels)$/,
	app_platform: "ReactJS",
	page_category: "SearchResults",
	currency: "@PATTERNS.currency",
	language: "@PATTERNS.language",
	isLoggedIn: "@PATTERNS.boolean",
	market: "@PATTERNS.market",
	marketLanguage: "@PATTERNS.marketLanguage",
	hToCode: "@PATTERNS.number",
	hToName: "@PATTERNS.anyText",
	hRooms: "@PATTERNS.number",
	hotelRoomDetails: "@PATTERNS.hotelRoomDetails",
	hFromCode: "@PATTERNS.number",
	hFromName: "@PATTERNS.anyText",
	hotel_upsellsource: false,
	sDateOutbound: "@PATTERNS.date",
	sDateInbound: "@PATTERNS.date",
	sTravelDuration: "@PATTERNS.number",
	sTravelHorizon: "@PATTERNS.number",
	sPaxAdult: "@PATTERNS.number",
	sPaxSenior: "@PATTERNS.number",
	sPaxChildren: "@PATTERNS.number",
	sPaxInfants: "@PATTERNS.number",
	sPaxYouth: "@PATTERNS.number",
	sPaxTotal: "@PATTERNS.number",
	sPaxYouthsAndChildren: "@PATTERNS.number",
	sYouthsAndChildrenAge: "",
	numberOfResults: "@PATTERNS.number",
	hHotelId: ["@PATTERNS.number"],
	hHotelName: ["@PATTERNS.anyText"],
	hHotelPackagePromotion: ["@PATTERNS.number"],
	hHotelPackageSavings: ["@PATTERNS.number"],
	hHotelPriceAllPassengers: ["@PATTERNS.number"],
	hHotelReviewCount: ["@PATTERNS.number"],
	hHotelReviewScore: ["@PATTERNS.hotelReviewScore"],
	hHotelStarRating: ["@PATTERNS.hotelStarRating"],
	hHotelSalesTag: ["@PATTERNS.anyText"],
	package_searchresults: "@PATTERNS.anyText",
	sort_by: /^price\:(asc|desc)$/,
	page_name: "SearchResultsList"
},
	{
	event: "TealiumView",
	ecommerce_action: "product view",
	app_name: /^(Packages|Hotels)$/,
	app_platform: "ReactJS",
	page_category: "HotelDetail",
	isLoggedIn: "@PATTERNS.boolean",
	marketLanguage: "@PATTERNS.marketLanguage",
	currency: "@PATTERNS.currency",
	market: "@PATTERNS.market",
	language: "@PATTERNS.language",
	sPaxAdult: "@PATTERNS.number",
	sPaxSenior: "@PATTERNS.number",
	sPaxChildren: "@PATTERNS.number",
	sPaxInfants: "@PATTERNS.number",
	sPaxYouth: "@PATTERNS.number",
	sPaxTotal: "@PATTERNS.number",
	sPaxYouthsAndChildren: "@PATTERNS.number",
	sYouthsAndChildrenAge: "",
	hToCode: "@PATTERNS.number",
	hToName: "@PATTERNS.anyText",
	hRooms: "@PATTERNS.number",
	hotelRoomDetails: "@PATTERNS.hotelRoomDetails",
	hFromCode: "@PATTERNS.number",
	hFromName: "@PATTERNS.anyText",
	hotel_upsellsource: false,
	sDateOutbound: "@PATTERNS.date",
	sDateInbound: "@PATTERNS.date",
	sTravelDuration: "@PATTERNS.number",
	sTravelHorizon: "@PATTERNS.number",
	hHotelDetails: /^.*\|\d+\|.*$/,
	hHotelId: ["@PATTERNS.number"],
	hHotelName: ["@PATTERNS.anyText"],
	hHotelReviewCount: ["@PATTERNS.number"],
	hHotelReviewScore: ["@PATTERNS.hotelReviewScore"],
	hHotelStarRating: ["@PATTERNS.hotelStarRating"],
	page_name: "HotelRooms"
},
  {
	app_platform: "ReactJS",
	app_name: "TravelExtras",
	market: "@PATTERNS.market",
	language: "@PATTERNS.language",
	currency: "@PATTERNS.currency",
	event: "TealiumView",
	sFromCode: "@PATTERNS.stationCode",
	sFromName: "@PATTERNS.requiredText",
	sToCode: "@PATTERNS.stationCode",
	sToName: "@PATTERNS.requiredText",
	sJourneyType: "@PATTERNS.journeyType",
	directOrConnection: "@PATTERNS.connectionType",
	specialBooking: "",
	sDateOutbound: "@PATTERNS.date",
	sTravelHorizon: "@PATTERNS.number",
	sPaxTotal: "@PATTERNS.number",
	sPaxSenior: "@PATTERNS.number",
	sPaxAdult: "@PATTERNS.number",
	sPaxYouth: "@PATTERNS.number",
	sPaxChildren: "@PATTERNS.number",
	sPaxInfants: "@PATTERNS.number",
	sPaxCompanion: "@PATTERNS.number",
	pointsOrRegular:"@PATTERNS.bookingType",
	basket_value: "@PATTERNS.number",
	basket_value_inpoints: "@PATTERNS.number",
	sTrainNumberOutbound: "@PATTERNS.trainNumber",
	sOutboundTime: "@PATTERNS.time",
	sClassOutbound: "@PATTERNS.trainClass",
	sTrainTarriffOutbound: /^[A-Z0-9]{11}$/,
	funnel_name: /^(Trains|Packages)$/,
	page_name: "TravelExtras"
},
	{
	event: "TealiumView",
	page_category: "Overview",
	isLoggedIn: "true",
	customer_hashedemail: "@PATTERNS.hashedEmail",
	customer_is_admin: "false",
	businessID: "@PATTERNS.businessId",
	loyaltyTier: "@PATTERNS.loyaltyTier",
	membershipID: "@PATTERNS.membershipId",
	membershipDetails: "@PATTERNS.anyText",
	pointsToSpend: "@PATTERNS.number",
    	pointsToUpgrade: "@PATTERNS.numberOptional",
	mktOptions: "false",
	page_name: "Overview"
},
	{
	currency: "@PATTERNS.currency", 
	funnel_name: /^(Trains|Packages|Hotels)$/, 
	page_category: "Login",
	ld_version: "design-system",
	event: "TealiumView",
	isLoggedIn: "false",
	page_name: "Login"
},
{
	event: "TealiumView",
	isLoggedIn: "false",
	currency: "@PATTERNS.currency",
	funnel_name: "Register",
	page_category: "Register",
	page_name: "Register"
},
{
	eventAction: "Forgotten your password",
	eventCategory: "Login or Register",
	formName: "header",
	eventName: "InteractionEvent",
	event: "TealiumLink"
},
{
	event: "TealiumView",
	isLoggedIn: "false",
	page_category: "ResetPassword",
    currency: "@PATTERNS.currency",
	funnel_name: "Register",
	page_name: "ResetPassword"
},
{
  event: "TealiumView",
  funnel_name: "ManageBooking",
  page_category: "Dashboard",
  ecommerce_action: "view booking",
  currency: "@PATTERNS.currency", 
  isLoggedIn: "@PATTERNS.boolean",
  customer_hashedemail: "@PATTERNS.hashedEmail",
  customer_is_admin: "@PATTERNS.booleanOptional",
  businessID: "@PATTERNS.businessId",
  loyaltyTier: "@PATTERNS.loyaltyTier",
  membershipID: "@PATTERNS.membershipId",
  membershipDetails: /^Points: \d+; Points to upgrade: \d+$/,
  pointsToSpend: "@PATTERNS.number",
  pointsToUpgrade: "@PATTERNS.numberOptional",
  mktOptions: "@PATTERNS.boolean",
  order_id: "@PATTERNS.orderId", 
  pnr: "@PATTERNS.pnr", 
  pointsOrRegular: "@PATTERNS.bookingType",
  purchase_hashedemail: "@PATTERNS.hashedEmail",
  transactionType: /^(train|package) booking$/,
  transactionCancelDate: /^(undefined|null|[\d-]{10})$/,
  passengerInformation: "@PATTERNS.boolean",
  sFromCode: "@PATTERNS.stationCode",
  sFromName: "@PATTERNS.requiredText",
  sToCode: "@PATTERNS.stationCode",
  sToName: "@PATTERNS.requiredText",
  sJourneyType: "@PATTERNS.journeyType",
  directOrConnection: "@PATTERNS.connectionType",
  sDateOutbound: "@PATTERNS.date",
  sDateInbound: /^(\d{4}-\d{2}-\d{2}|null|undefined)?$/,
  sTravelHorizon: "@PATTERNS.number",
  sTravelDuration: "@PATTERNS.number",
  sPaxTotal: "@PATTERNS.number",
  sPaxAdult: "@PATTERNS.number",
  sPaxChildren: "@PATTERNS.number",
  sPaxInfants: "@PATTERNS.number",
  sPaxSenior: "@PATTERNS.number",
  sPaxYouth: "@PATTERNS.number",
  sPaxCompanion: "@PATTERNS.number",
  sClassOutbound: "@PATTERNS.trainClass",
  sOutboundTime: "@PATTERNS.time",
  sESTrainNumberOutbound: /^\d{4}?$/,
  sClassInbound: /^Eurostar (Standard|Plus|Premier)|null|undefined$/,
  sInboundTime: /^\d{2}:\d{2}|null|undefined$/,
  sESTrainNumberInbound: /^\d{4}|null|undefined$/,
  products_count: "@PATTERNS.number",
  product_status: ["@PATTERNS.bookingStatus"],
  product_name: [/^\d{7} - \d{7}(:adult)|(Cancellation|Comprehensive) insurance|(.*)?$/],
  product_id: [/^(?:\d{7} - \d{7}|[A-Za-z0-9]+)$/],
  product_quantity: ["@PATTERNS.number"],
  product_price: ["@PATTERNS.priceDecimal"],
  product_brand: [/^(ES|ER|Allianz|.*)$/],
  product_category: [/^(trains|insurance|hotels)$/],
  product_variant: [/^(outbound|inbound|cancellation|comprehensive|.*)$/],
  product_departure_date: [/^(\d{4}-\d{2}-\d{2}|null)$/],
  product_return_date: ["@PATTERNS.dateOptional"],
  product_train_class: [/^Eurostar (Standard|Plus|Premier)|null$/],
  product_train_route: [/^(london route|continent route|null)$/],
  product_train_origin_stationcode: [/^\d{7}|null$/],
  product_train_destination_stationcode: [/^\d{7}|null$/],
  product_train_number: [/^\d{4}|null$/],
  product_train_fbccode: ["@PATTERNS.anyText"],
  product_train_departuretime: [/^\d{2}:\d{2}|null$/],
  product_train_arrivaltime: [/^\d{2}:\d{2}|null$/],
  product_train_numberofconnections: [/^\d+|null$/],
  product_train_connectioncode: [/^(null|\d{7})$/],
  product_train_connectionoperator: ["@PATTERNS.connectionOperator"],
  product_train_tickettype: [/^(ESTAR_PUB_(STD|PLUS|PREM)|SNCF1SF|RED_ESTAR_PUB_PLUS|RID_STD|null)$/],
  product_train_passenger_type: ["@PATTERNS.passengerType"],
  product_hotel_destination_code: [],
  product_hotel_starrating: [],
  product_hotel_origin_code: [],
  product_hotel_occupancy: [],
  product_hotel_review_count: [],
  product_hotel_review_score: [],
  product_hotel_room_extra: [],
  product_hotel_promotion: [],
  product_hotel_package_savings: [],
  product_train_fare_name: [/^(through fare|null)?$/],
  product_train_fare_type: [/^(ES_ER|ER_SN|null)?$/],
  page_name: "ManageYourBooking"
},
{
	currency: "@PATTERNS.currency", 
	funnel_name: "@PATTERNS.funnelName",
	page_category: "Checkout",
	ld_version: "design-system",
	event: "TealiumView",
	activityType: /^(train exchange|package exchange|hotel exchange|loyalty exchange)$/,
	isLoggedIn: "@PATTERNS.boolean",
        customer_hashedemail: /^.{0,64}$/,
        customer_is_admin: "@PATTERNS.booleanOptional",
        businessID: "@PATTERNS.businessId",
        loyaltyTier: "@PATTERNS.loyaltyTier",
	membershipID: "@PATTERNS.membershipId",
        membershipDetails: /^.{0,100}$/,
        pointsToSpend: "@PATTERNS.number",
        pointsToUpgrade: "@PATTERNS.number",
	directOrConnection: "@PATTERNS.connectionType",
        sJourneyType: "@PATTERNS.journeyType",
        sFromCode: "@PATTERNS.stationCode",
        sFromName: "@PATTERNS.requiredText",
        sToCode: "@PATTERNS.stationCode",
        sToName: "@PATTERNS.requiredText",
        sDateOutbound: "@PATTERNS.date",
        sDateInbound: /^$|^\d{4}-\d{2}-\d{2}$/,
        sTravelHorizon: "@PATTERNS.number",
        sTravelDuration: "@PATTERNS.numberOptionalExtended",
        sPaxTotal: "@PATTERNS.number",
        sPaxAdult: "@PATTERNS.number",
        sPaxChildren: "@PATTERNS.number",
        sPaxInfants: "@PATTERNS.number",
        sPaxSenior: "@PATTERNS.number",
        sPaxYouth: "@PATTERNS.number",
        sPaxCompanion: "@PATTERNS.number",
	basket_value_inpoints: "@PATTERNS.number",
        pointsOrRegular: "@PATTERNS.bookingType",
        promoBooking: "@PATTERNS.anyText",
        ecommerce_action: "checkout",
	payment_methods: "@PATTERNS.paymentMethods",
        club_eurostar_discount: "@PATTERNS.clubDiscount",
	basket_value: "@PATTERNS.priceDecimalOptional",
	products_count: "@PATTERNS.number",
	product_brand: [/^(Allianz|ES|ER)$/],
	product_id: [/^(\d{7}( - \d{7})?|.*)$/],
	product_category: [/^(trains|insurance)$/],
        product_name: [/^(\d{7} - \d{7}:adult|.*insurance)$/],
        product_price: ["@PATTERNS.priceDecimal"],
        product_price_inpoints: ["@PATTERNS.numberOptionalExtended"],
	product_quantity: ["@PATTERNS.number"],
        product_train_numberofconnections: ["@PATTERNS.numberOptionalExtended"],
        product_departure_date: ["@PATTERNS.date"],
	product_train_departuretime: ["@PATTERNS.time"],
        product_train_fbccode: ["@PATTERNS.requiredText"],
        product_train_number: ["@PATTERNS.number"],
        product_variant: [/^(outbound|inbound|comprehensive)$/],
	product_hotel_origin_code: [/^(\d+|null|unudefined)$/],
        product_hotel_destination_code: [/^(\d+|null|unudefined)$/],
        product_hotel_occupancy: [/^(\d+|null|unudefined)$/],
        product_hotel_starrating: [/^(\d+|null|unudefined)$/],
        product_hotel_review_count: [/^(\d+|null|unudefined)$/],
        product_hotel_review_score: [/^(\d+|null|unudefined)$/],
        product_hotel_room_extra: [/^(\d+|null|unudefined)$/],
	product_return_date: ["@PATTERNS.dateOptional"],
        product_train_class: ["@PATTERNS.trainClass"],
        product_train_route: ["@PATTERNS.trainRoute"],
        product_train_origin_stationcode: ["@PATTERNS.stationCode"],
        product_train_destination_stationcode: ["@PATTERNS.stationCode"],
        product_train_arrivaltime: ["@PATTERNS.time"],
        product_train_tickettype: ["@PATTERNS.trainTicketType"],
        product_train_connectionoperator: ["@PATTERNS.connectionOperator"],
        product_train_passenger_type: ["@PATTERNS.passengerType"],
        product_train_fare_name: [/^(through fare|sumated fare|null|undefined)?$/],
        product_train_fare_type: [/^(ES_ER|ER_SN|null)?$/],
	product_cancellation_policy: [null],
	page_name: "Checkout"
},
{
	event: "TealiumView",
	funnel_name: "ManageBooking",
	page_category: "Upgrade",
	currency: "@PATTERNS.currency", 
	ecommerce_action: "product impressions",
	isLoggedIn: "@PATTERNS.boolean",
        customer_hashedemail: /^.{0,64}$/,
        customer_is_admin: "@PATTERNS.booleanOptional",
        businessID: "@PATTERNS.businessId",
        loyaltyTier: "@PATTERNS.loyaltyTier",
	membershipID: "@PATTERNS.membershipId",
        membershipDetails: /^.{0,100}$/,
	pointsToSpend: "@PATTERNS.number",
        pointsToUpgrade: "@PATTERNS.number",
	mktOptions: "@PATTERNS.boolean",
	pnr: "@PATTERNS.pnr", 
	purchase_hashedemail: /^.{0,64}$/,
	transaction_date: /^[\d-]{8}$/,
	sFromCode: "@PATTERNS.stationCode",
        sFromName: "@PATTERNS.requiredText",
        sToCode: "@PATTERNS.stationCode",
        sToName: "@PATTERNS.requiredText",
	sJourneyType: "@PATTERNS.journeyType",
	directOrConnection: "@PATTERNS.connectionType",
	sDateOutbound: /^$|undefined|\d{4}-\d{2}-\d{2}$/,
        sDateInbound: /^$|undefined|^\d{4}-\d{2}-\d{2}$/,
	sTravelHorizon: "@PATTERNS.number",
        sTravelDuration: "@PATTERNS.numberOptional",
        sPaxTotal: "@PATTERNS.number",
        sPaxAdult: "@PATTERNS.number",
        sPaxChildren: "@PATTERNS.number",
        sPaxInfants: "@PATTERNS.number",
        sPaxSenior: "@PATTERNS.number",
        sPaxYouth: "@PATTERNS.number",
        sPaxCompanion: "@PATTERNS.number",
	product_brand: ["@PATTERNS.trainBrand"],
	product_category: ["trains"],
	product_departure_date: ["@PATTERNS.date"],
	product_id: [/^\d{7} - \d{7}$/],
	product_name: [/^\d{7} - \d{7}(:adult)?$/], // as array
	product_price: ["@PATTERNS.priceDecimal"],
	product_quantity: ["@PATTERNS.number"],
	product_return_date: ["@PATTERNS.dateOptional"],
	product_train_arrivaltime: ["@PATTERNS.time"],
	product_train_class: ["@PATTERNS.trainClass"],
	product_train_connectioncode: [/^(null|\d{7})$/],
	product_train_connectionoperator: ["@PATTERNS.connectionOperator"],
	product_train_departuretime: ["@PATTERNS.time"],
	product_train_destination_stationcode: ["@PATTERNS.stationCode"],
	product_train_fbccode: ["@PATTERNS.anyText"],
	product_train_number: ["@PATTERNS.trainNumber"],
	product_train_numberofconnections: ["@PATTERNS.number"],
	product_train_origin_stationcode: ["@PATTERNS.stationCode"],
	product_train_passenger_type: ["@PATTERNS.passengerType"],
	product_train_route: ["@PATTERNS.trainRoute"],
	product_train_tickettype: [/^(ESTAR_PUB_(STD|PLUS|PREM)|SNCF1SF|RED_ESTAR_PUB_PLUS)$/],
	product_variant: ["@PATTERNS.productVariant"],
	products_count: "@PATTERNS.number",
	page_name: "Upgrade/SelectUpgrade"
},
{
	event: "TealiumView",
	page_category: "Bookings",
	isLoggedIn: "true",
	customer_hashedemail: "@PATTERNS.hashedEmail",
	customer_is_admin: "false",
	businessID: "@PATTERNS.businessId",
	loyaltyTier: "@PATTERNS.loyaltyTier",
	membershipID: "@PATTERNS.membershipId",
	membershipDetails: "@PATTERNS.anyText",
	pointsToSpend: "@PATTERNS.number",
    	pointsToUpgrade: "@PATTERNS.numberOptional",
	mktOptions: "@PATTERNS.boolean",
	page_name: /^Bookings\/(Upcoming|Past|Cancelled)Bookings$/
},
{
	event: "TealiumView",
	page_category: "Loyalty Membership",
	isLoggedIn: "true",
	customer_hashedemail: "@PATTERNS.hashedEmail",
	customer_is_admin: "false",
	businessID: "@PATTERNS.businessId",
	loyaltyTier: "@PATTERNS.loyaltyTier",
	membershipID: "@PATTERNS.membershipId",
	membershipDetails: "@PATTERNS.anyText",
	pointsToSpend: "@PATTERNS.number",
    	pointsToUpgrade: "@PATTERNS.numberOptional",
	mktOptions: "@PATTERNS.boolean",
	page_name: /^(SpendPoints|ClubLevels|ClubVouchers|PartnerOffers|PointsStatement|ClaimMissingPoints|SharePoints)$/
},
{
	event: "TealiumView",
	page_category: "Settings",
	isLoggedIn: "true",
	customer_hashedemail: "@PATTERNS.hashedEmail",
	customer_is_admin: "false",
	businessID: "@PATTERNS.businessId",
	loyaltyTier: "@PATTERNS.loyaltyTier",
	membershipID: "@PATTERNS.membershipId",
	membershipDetails: "@PATTERNS.anyText",
	pointsToSpend: "@PATTERNS.number",
    	pointsToUpgrade: "@PATTERNS.numberOptional",
	mktOptions: "@PATTERNS.boolean",
	page_name: /^Settings\/(YourDetails|AdvancePassengerInformation|ChangeEmail|PasswordAndSecurity|CommunicationPreferences|PaymentCards|AccountOptions|SavedPassengers)$/
},

{
	event: "TealiumView",
	page_category: "SubscriptionPasses",
	isLoggedIn: "true",
	customer_hashedemail: "@PATTERNS.hashedEmail",
	customer_is_admin: "false",
	businessID: "@PATTERNS.businessId",
	loyaltyTier: "@PATTERNS.loyaltyTier",
	membershipID: "@PATTERNS.membershipId",
	membershipDetails: "@PATTERNS.anyText",
	pointsToSpend: "@PATTERNS.number",
    	pointsToUpgrade: "@PATTERNS.numberOptional",
	mktOptions: "@PATTERNS.boolean",
	page_name: /^SubscriptionPasses\/(Current|Past)$/
},
{
	event: "TealiumView",
	app_name: "OneCheckout",
	app_platform: "ReactJS",
	app_type: "web",
	currency: "@PATTERNS.currency",
	funnel_name: "@PATTERNS.funnelName",
	language: "@PATTERNS.language",
	market: "@PATTERNS.market",
	page_category: /^(BookingConfirmation|Upgrade|Exchange)$/,
	isLoggedIn: "true",
	customer_is_admin: "false",
	businessID: "@PATTERNS.businessId",
	customer_hashedemail: "@PATTERNS.hashedEmail",
	loyaltyTier: "@PATTERNS.loyaltyTier",
	membershipID: "@PATTERNS.membershipId",
	ld_version: "design-system",
	eventName: "ImpressionEcommerceEvent",
	ecommerce_action: "purchase",
	eventCategory: "Ecommerce",
	eventAction: "Purchase",
	eventLabel: /^Train booking\:regular (booking|upgrade|exchange)$/,
	eventNonInteraction: true,
	pnr: "@PATTERNS.pnr", 
	order_id: "@PATTERNS.orderId",
	order_revenue: "@PATTERNS.priceDecimal",
	order_revenue_inpoints: "@PATTERNS.number",
	purchase_hashedemail: /^.{0,64}$/,
	pointsOrRegular: /^(regular booking|points booking|club voucher)$/,
	transactionType: /^(train booking|hotel booking|package booking|subscription booking)$/,
	paymentDetails: "@PATTERNS.paymentDetails",
	paymentCardType: "@PATTERNS.paymentCardType",
	payment_status: /^(confirmed|pending)$/,
	loyalty_points_discount_usage: "@PATTERNS.boolean",
	loyalty_points_discount_value: /^(null|\d+\.\d{2})$/,
	voucher_usage: /^(Yes|No)$/,
	voucher_code: /^(undefined|.*)$/,
	voucher_value: /^(null|.*)$/,
	discount_code: /^(null|.*)$/,
	discount_value: /^(null|.*)$/,
	directOrConnection: "@PATTERNS.connectionType",
	sJourneyType: "@PATTERNS.journeyType",
	sFromCode: "@PATTERNS.stationCode",
	sFromName: "@PATTERNS.requiredText",
	sToCode: "@PATTERNS.stationCode",
	sToName: "@PATTERNS.requiredText",
	sDateOutbound: "@PATTERNS.date",
	sDateInbound: "@PATTERNS.date",
	sTravelHorizon: "@PATTERNS.number",
	sTravelDuration:"@PATTERNS.number",
	sPaxAdult: "@PATTERNS.number",
    sPaxChildren: "@PATTERNS.number",
    sPaxYouth: "@PATTERNS.number",
    sPaxInfants: "@PATTERNS.number",
    sPaxSenior: "@PATTERNS.number",
    sPaxCompanion: "@PATTERNS.companionCount",
    sPaxTotal: "@PATTERNS.number",
	products_count: "@PATTERNS.number",
	product_name: [/^\d{7} - \d{7}(:adult)?$/], // as array
	product_id: [/^\d{7} - \d{7}$/],
	product_quantity: ["@PATTERNS.number"],
	product_price: ["@PATTERNS.priceDecimal"],
	product_price_inpoints: ["@PATTERNS.numberOptionalExtended"],
	product_brand: ["@PATTERNS.trainBrand"],
	product_category: ["trains"],
	product_variant: ["@PATTERNS.productVariant"],
	product_departure_date: [/^(\d{4}-\d{2}-\d{2}|null)$/],
	product_return_date: ["@PATTERNS.dateOptional"],
	product_train_class: ["@PATTERNS.trainClass"],
	product_train_route: ["@PATTERNS.trainRoute"],
	product_train_origin_stationcode: ["@PATTERNS.stationCode"],
	product_train_destination_stationcode: ["@PATTERNS.stationCode"],
	product_train_number: ["@PATTERNS.trainNumber"],
	product_train_fbccode: ["@PATTERNS.anyText"],
	product_train_departuretime: ["@PATTERNS.time"],
	product_train_arrivaltime: ["@PATTERNS.time"],
	product_train_numberofconnections: ["@PATTERNS.number"],
	product_train_connectioncode: [/^(null|\d{7})$/],
	product_train_connectionoperator: ["@PATTERNS.connectionOperator"],
	product_train_tickettype: [/^(ESTAR_PUB_(STD|PLUS|PREM)|SNCF1SF|RED_ESTAR_PUB_PLUS)$/],
	product_train_passenger_type: ["@PATTERNS.passengerType"],
	product_train_fare_name: [],
	product_train_fare_type: [],
	product_hotel_destination_code: [],
	product_hotel_starrating: [],
	product_cancellation_policy: [/^null$/],
	page_name: /^(Upgrade|Exchange)?(\/)?BookingConfirmation$/
},
{
	event: "TealiumView",
	funnel_name: "ManageBooking",
	page_category: "RetrieveBooking",
	isLoggedIn: "true",
	customer_hashedemail: "@PATTERNS.hashedEmail",
	customer_is_admin: "false",
	businessID: "@PATTERNS.businessId",
	loyaltyTier: "@PATTERNS.loyaltyTier",
	membershipID: "@PATTERNS.membershipId",
	membershipDetails: "@PATTERNS.anyText",
	pointsToSpend: "@PATTERNS.number",
    	pointsToUpgrade: "@PATTERNS.numberOptional",
	mktOptions: "@PATTERNS.boolean",
	page_name: "RetrieveYourBooking"
},
{
	event: "TealiumView",
	funnel_name: "ManageBooking",
	page_category: "Exchange",
	currency: "@PATTERNS.currency",
	isLoggedIn: "true",
	customer_hashedemail: "@PATTERNS.hashedEmail",
	customer_is_admin: "false",
	businessID: "@PATTERNS.businessId",
	loyaltyTier: "@PATTERNS.loyaltyTier",
	membershipID: "@PATTERNS.membershipId",
	membershipDetails: "@PATTERNS.anyText",
	pointsToSpend: "@PATTERNS.number",
    	pointsToUpgrade: "@PATTERNS.numberOptional",
	mktOptions: "@PATTERNS.boolean",
	pnr: "@PATTERNS.pnr", 
	pointsOrRegular: "@PATTERNS.bookingType",
	purchase_hashedemail: /^.{0,64}$/,
	transaction_date: "@PATTERNS.transactionDate",
	activityType: /^(package|hotel|train) exchange$/,
	page_name: "Exchange/SelectTravelDates"
},
  {
	app_type: "web",
	market: "@PATTERNS.market",
	funnel_name: "ManageBooking",
	page_category: "Exchange",
	isLoggedIn: "true",
	customer_hashedemail: "@PATTERNS.hashedEmail",
	customer_is_admin: "false",
	businessID: "@PATTERNS.businessId",
	loyaltyTier: "@PATTERNS.loyaltyTier",
	membershipID: "@PATTERNS.membershipId",
	membershipDetails: "@PATTERNS.anyText",
	pointsToSpend: "@PATTERNS.number",
	pointsToUpgrade: "@PATTERNS.numberOptional",
	mktOptions: "@PATTERNS.boolean",
	pnr: "@PATTERNS.pnr", 
	transaction_date: "@PATTERNS.transactionDate",
	purchase_hashedemail: "@PATTERNS.hashedEmail",
	isHeterogeneous: "false",
	directOrConnection: "direct",
	sJourneyType: "@PATTERNS.journeyType",
	sFromCode: "@PATTERNS.stationCode",
	sFromName: "@PATTERNS.requiredText",
	sToCode: "@PATTERNS.stationCode",
	sToName: "@PATTERNS.requiredText",
	sDateOutbound: "2025-08-11",
	sDateInbound: "2025-08-14",
	sTravelHorizon: "@PATTERNS.number",
	sTravelDuration: "@PATTERNS.number",
	sPaxAdult: "@PATTERNS.number",
	sPaxChildren: "@PATTERNS.number",
	sPaxYouth: "@PATTERNS.number",
	sPaxInfants: "@PATTERNS.number",
	sPaxSenior: "@PATTERNS.number",
	sPaxCompanion: "@PATTERNS.companionCount",
	sPaxTotal: "@PATTERNS.number",
	basket_value_inpoints: "@PATTERNS.number",
	refundAmount: "@PATTERNS.number",
	pointsOrRegular: "regular booking",
	activityType: "train exchange",
	page_name: "Exchange/ReviewExchange",
	event: "TealiumView"
  },
{
	event: "TealiumView",
	currency: "@PATTERNS.currency",
	sFromCode: "@PATTERNS.stationCode",
	sFromName: "@PATTERNS.requiredText",
	sToCode: "@PATTERNS.stationCode",
	sToName: "@PATTERNS.requiredText",
	sJourneyType: "@PATTERNS.journeyType",
	sPaxAdult: "@PATTERNS.number",
	sPaxChildren: "@PATTERNS.number",
	sPaxYouth: "@PATTERNS.number",
	sPaxInfants: "@PATTERNS.number",
	sPaxSenior: "@PATTERNS.number",
	sPaxCompanion: "@PATTERNS.companionCount",
	sPaxTotal: "@PATTERNS.number",
	sDateOutboundBookingMonth: /^\d{4}_\S{3}$/,
	sDateInboundBookingMonth: /^\d{4}_\S{3}$/,
	sOutboundLowestFare: "@PATTERNS.number",
	sInboundLowestFare: "@PATTERNS.number",
	pointsOrRegular: "regular booking",
	page_name: "LowestFareFinder"
},
{
	event: "TealiumView",
	funnel_name: "ManageBooking",
	page_category: "Cancellation",
	currency: "@PATTERNS.currency",
	activityType: "package:card refund",
	isLoggedIn: "true",
	customer_hashedemail: "@PATTERNS.hashedEmail",
	customer_is_admin: "false",
	businessID: "@PATTERNS.businessId",
	loyaltyTier: "@PATTERNS.loyaltyTier",
	membershipID: "@PATTERNS.membershipId",
	membershipDetails: "@PATTERNS.anyText",
	pointsToSpend: "@PATTERNS.number",
	pointsToUpgrade: "@PATTERNS.numberOptional",
	mktOptions: "@PATTERNS.boolean",
	pnr: "@PATTERNS.pnr",
	pointsOrRegular: "@PATTERNS.bookingType",
	purchase_hashedemail: "@PATTERNS.hashedEmail",
	transaction_date: "@PATTERNS.transactionDate",
	page_name: "Cancellation/ReviewCancellation"
},{
	event: "TealiumView",
	funnel_name: "ManageBooking",
	page_category: "Cancellation",
	currency: "@PATTERNS.currency",
	isLoggedIn: "true",
	customer_hashedemail: "@PATTERNS.hashedEmail",
	customer_is_admin: "false",
	businessID: "@PATTERNS.businessId",
	loyaltyTier: "@PATTERNS.loyaltyTier",
	membershipID: "@PATTERNS.membershipId",
	membershipDetails: "@PATTERNS.anyText",
	pointsToSpend: "@PATTERNS.number",
	pointsToUpgrade: "@PATTERNS.numberOptional",
	mktOptions: "@PATTERNS.boolean",
	pnr: "@PATTERNS.pnr",
	order_id: "@PATTERNS.orderIdCancelled",
	pointsOrRegular: "@PATTERNS.bookingType",
	purchase_hashedemail: "@PATTERNS.hashedEmail",
	transaction_date: "@PATTERNS.transactionDate",
	sPaxTotal: "@PATTERNS.number",
	sPaxAdult: "@PATTERNS.number",
	sPaxChildren: "@PATTERNS.number",
	sPaxInfants: "@PATTERNS.number",
	sPaxSenior: "@PATTERNS.number",
	sPaxYouth: "@PATTERNS.number",
	sPaxCompanion: "@PATTERNS.companionCount",
	activityType: "package:card refund",
	ecommerce_action: "refund",
	eventName: "ImpressionEcommerceEvent",
	eventCategory: "Ecommerce refund",
	eventAction: "package:card refund",
	eventLabel: "package:card refund:GBP:full",
	eventNonInteraction: true,
	transactionCancelDate: /^\d{8}$/,
	transactionType: "package:card refund",
	refundAmount: "@PATTERNS.number",
	refundJourneyType: "full",
	products_count: "@PATTERNS.number",
	product_status: ["@PATTERNS.cancellationStatus"],
	product_name: [/^\d{7} - \d{7}:adult|(.*\:\d+)?$/],
	product_id: [/^\d{7} - \d{7}|(\d+)?$/],
	product_quantity: ["@PATTERNS.number"],
	product_price: ["@PATTERNS.priceDecimal"],
	product_brand: [/^(ES|ER|.*)$/],
	product_category: [/^(trains|insurance|hotels)$/],
	product_variant: [/^(outbound|inbound|cancellation|comprehensive|.*)$/],
	product_departure_date: [/^\d{4}-\d{2}-\d{2}|null$/],
	product_return_date: ["@PATTERNS.dateOptional"],
	product_train_class: [/^Eurostar (Standard|Plus|Premier)|null$/],
	product_train_route: [/^(london route|continent route|null)$/],
	product_train_origin_stationcode: [/^\d{7}|null$/],
	product_train_destination_stationcode: [/^\d{7}|null$/],
	product_train_number: [/^\d{4}|null$/],
	product_train_fbccode: ["@PATTERNS.anyText"],
	product_train_departuretime: [/^\d{2}:\d{2}|null$/],
	product_train_arrivaltime: [/^\d{2}:\d{2}|null$/],
	product_train_numberofconnections: [/^\d+|null$/],
	product_train_connectioncode: [],
	product_train_connectionoperator: [],
	product_train_tickettype: ["@PATTERNS.trainTicketType"],
	product_train_passenger_type: ["@PATTERNS.passengerType"],
	product_hotel_destination_code: [/^\d{3}|null$/],
	product_hotel_starrating: [/^\d|null$/],
	product_hotel_origin_code: [/^\d{3}|null$/],
	product_hotel_occupancy: [/^\d+|null$/],
	product_hotel_review_count: [/^\d+|null$/],
	product_hotel_review_score: [/^\d(\.\d)?|null$/],
	product_hotel_room_extra: ["@PATTERNS.hotelRoomExtra"],
	product_hotel_promotion: ["@PATTERNS.hotelPackageSavings"],
	product_hotel_package_savings: [/^\d+|null$/],
	product_train_fare_name: [],
	product_train_fare_type: [],
	sDateOutbound: "@PATTERNS.date",
	sDateInbound: "@PATTERNS.date",
	sTravelHorizon: "@PATTERNS.number",
	sTravelDuration: "@PATTERNS.number",
	sFromCode: "@PATTERNS.stationCode",
	sFromName: "@PATTERNS.anyText",
	sToCode: "@PATTERNS.stationCode",
	sToName: "@PATTERNS.anyText",
	sJourneyType: "@PATTERNS.journeyType",
	directOrConnection: "@PATTERNS.connectionType",
	page_name: "Cancellation/Confirmation"
}	
];