// Tealium Link Event Templates using centralized patterns
// This file contains all TealiumLink specifications built from pattern references
// Requires patterns.js to be loaded first

window.expectedTealiumLinkObjects = [
{
	eventAction: "OnClick",
	destinationUrl: "@PATTERNS.anyText",
	eventCategory: /^(Header|Footer)Link$/,
	eventLabel: /^(TopMenu_)?(.*)$/,
	eventName: /^NavigationEvent_v(\d{1})$/,
	event: "TealiumLink",
},
{
  "eventCategory": "Internal Promotion",
  "eventAction": "Impression",
  "eventNonInteraction": true,
  "eventLabel": "@PATTERNS.anyText",
  "promotion_id": ["@PATTERNS.anyText"],
  "promotion_name": ["@PATTERNS.anyText"],
  "promotion_creative": ["@PATTERNS.anyText"],
  "promotion_position": ["@PATTERNS.promotionPosition"],
  "page_element_cta": "@PATTERNS.requiredText",
  "eventName": "ImpressionEvent",
  "event": "TealiumLink"
},	
{
	"eventAction": "Click",
	"eventCategory": "Internal Promotion",
	"promotion_name": ["@PATTERNS.anyText"],
	"promotion_position": ["@PATTERNS.promotionPosition"],
	"page_element_cta": "@PATTERNS.anyText",
	"eventLabel": "@PATTERNS.anyText",
	"promotion_id": ["@PATTERNS.anyText"],
	"promotion_creative": ["@PATTERNS.anyText"],
	"eventName": "InteractionEvent",
	"event": "TealiumLink"
},
{
	eventCategory: "Border Requirements",
	eventAction: "@PATTERNS.bookingMagnetActions",
	eventLabel: "@PATTERNS.bookingMagnetLabels",
	eventName: "InteractionEvent",
	destinationUrl: "@PATTERNS.anyText",
	event: "TealiumLink"
},
{
	event: "TealiumLink",
	eventName: "InteractionEvent",
	eventCategory: "Accordion",
	eventAction: "Expand",
	eventLabel: "Entry / Exit System (EES):Complete Check"
},	
{
  "eventAction": "Expand",
  "eventCategory": "Booking Magnet",
  "eventLabel": /^(P|H|T)(:Expand)$/,
  "interactionSection": "header",
  "eventName": "InteractionEvent",
  "event": "TealiumLink"
},
{
  "eventAction": "Collapse",
  "eventCategory": "Booking Magnet",
  "eventLabel": /^(P|H|T)(:Collapse)$/,
  "interactionSection": "header",
  "eventName": "InteractionEvent",
  "event": "TealiumLink"
},	
{
  "eventAction": "Field Start",
  "eventLabel": /^(T|P|H):(To|From)$/,
  "eventCategory": "Booking Magnet",
  "interactionSection": "header",
  "eventName": "InteractionEvent",
  "event": "TealiumLink"
},
{
  "eventAction": "Field Completion",
  "eventLabel": /^(T:From_\d{7}|P:From_\d{3}|H:From_\d{3})$/,
  "eventCategory": "Booking Magnet",
  "interactionSection": "header",
  "eventName": "InteractionEvent",
  "event": "TealiumLink"
},
{
  "eventAction": "Field Completion",
  "eventLabel": /^(T:To_\d{7}|P:To_\d{3}|H:To_\d{3})$/,
  "eventCategory": "Booking Magnet",
  "interactionSection": "header",
  "eventName": "InteractionEvent",
  "event": "TealiumLink"
},
{
  "eventAction": "Field Completion",
  "eventLabel": /^(T|P|H):(Calendar|Outbound|Inbound)$/,
  "eventCategory": "Booking Magnet",
  "interactionSection": "header",
  "eventName": "InteractionEvent",
  "event": "TealiumLink",
  "product": /^(trains|packages|hotels)$/
},
{
  "eventAction": "Field Start",
  "eventLabel": /^(T|P|H):(Calendar|Outboubd|Inbound)$/,
  "eventCategory": "Booking Magnet",
  "interactionSection": "header",
  "eventName": "InteractionEvent",
  "event": "TealiumLink"
},
{
  "eventAction": "Field Start",
  "eventLabel": /^(T|P|H):Passenger$/,
  "eventCategory": "Booking Magnet",
  "interactionSection": "header",
  "eventName": "InteractionEvent",
  "event": "TealiumLink"
},
{
  "eventAction": "Field Completion",
  "eventLabel": /^(T|P|H):Passenger$/,
  "eventCategory": "Booking Magnet",
  "interactionSection": "header",
  "eventName": "InteractionEvent",
  "event": "TealiumLink"
},
{
	eventAction: "Click",
	eventLabel: /^(T|P|H):Explore all(.*)$/, 
	eventCategory: "Booking Magnet",
	interactionSection: "header",
	eventName: "InteractionEvent",
	event: "TealiumLink"
},
{
	eventAction: "Click",
	eventLabel: /^(T|P|H):Groups 10\+$/,
	eventCategory: "Booking Magnet",
	interactionSection: "header",
	eventName: "InteractionEvent",
	event: "TealiumLink"
},
{
	eventAction: "Click",
	eventLabel: /^(T|P|H):(Search|Edit|Close|Find lowest fares)$/,
	eventCategory: "Booking Magnet",
	interactionSection: "header",
	eventName: "InteractionEvent",
	event: "TealiumLink"
},
  {
	eventAction: "Click",
	eventLabel: /^(T|P|H):Select (Out|In)bound Month$/,
	eventCategory: "Booking Magnet",
	interactionSection: "header",
	formName: "bm-no-pricing",
	eventName: "InteractionEvent",
	event: "TealiumLink",
},
{
	eventAction: "OnClick",
	eventCategory: "SearchResults_TravelClassInfo",
	eventLabel: "SearchResults_TravelClassInfo",
	eventName: "InteractionEvent",
	event: "TealiumLink"
},	
{
	eventAction: "OnClick",
	eventCategory: /^SearchResults_TimeAnchor_(out|in)bound$/,
	eventLabel: /^SearchResults_TimeAnchor_(out|in)bound_(morning|afternoon|evening)_(EUR|GBP|USD)_\d+$/,
	eventName: "InteractionEvent",
	event: "TealiumLink"
},
{
  "eventAction": "Select Outbound",
  "eventCategory": "Train Selection",
  "eventLabel": /^(Eurostar Standard|Eurostar Plus|Eurostar Premier)(\|.*)?$/,
  "noChanges": /^(0|null|undefined)$/,
  "sClassOutbound": "@PATTERNS.trainClass",
  "sOutboundTime": "@PATTERNS.time", 
  "sOutboundTime": "@PATTERNS.time", 
  "sOutboundConnectionCode": "@PATTERNS.connectionCode", 
  "sOutboundConnectionOperator": /^(null|undefined)$/,
  "sTrainNumberOutbound": "@PATTERNS.trainNumber",
  "sTrainTarriffOutbound": "@PATTERNS.trainTariff",
  "basket_value": "@PATTERNS.priceRange",
  "sTrainSaleTagsOutbound": /^(null|undefined|lowest fare|[A-Z0-9]+)$/,
  "basket_value_inpoints": "@PATTERNS.priceRange",
  "priceAdultOutbound": "@PATTERNS.priceDecimal",
  "priceChildOutbound": "@PATTERNS.priceDecimal",
  "priceYouthOutbound": "@PATTERNS.priceDecimal",
  "priceSeniorOutbound": "@PATTERNS.priceDecimal",
  "sTrainTypeOutbound": /^(ESTAR_PUB_(STD|PLUS|PREM)|RED_RIT_(STD|SP|BP))$/,
  "eventName": "InteractionEvent",
  "event": "TealiumLink"
},
{
  "eventAction": "Select Inbound",
  "eventCategory": "Train Selection",
  "eventLabel": /^(Eurostar Standard|Eurostar Plus|Eurostar Premier)(\|.*)?$/,
  "noChanges": /^(0|null|undefined)$/,
  "sClassInbound": "@PATTERNS.trainClass",
  "sInboundTime": "@PATTERNS.time",
  "sInboundArrivalTime": "@PATTERNS.time",
  "sInboundConnectionCode": "@PATTERNS.connectionCode", 
  "sInboundConnectionOperator": "@PATTERNS.connectionOperatorInbound",
  "sTrainNumberInbound": "@PATTERNS.trainNumberInbound",
  "sTrainTarriffInbound": "@PATTERNS.trainTariffOptional",
  "basket_value": "@PATTERNS.priceRange",
  "sTrainSaleTagsInbound": "@PATTERNS.anyText",
  "basket_value_inpoints": "@PATTERNS.priceRange",
  "priceAdultInbound": "@PATTERNS.priceDecimal",
  "priceChildInbound": "@PATTERNS.priceDecimal",
  "priceYouthInbound": "@PATTERNS.priceDecimal",
  "priceSeniorInbound": "@PATTERNS.priceDecimal",
  "sTrainTypeInbound": /^(ESTAR_PUB_(STD|PLUS|PREM)|RED_RIT_(STD|SP|BP))$/,
  "eventName": "InteractionEvent",
  "event": "TealiumLink"
},
{
  "eventAction": "Open Outbound Fare Details",
  "eventCategory": "Train Selection",
  "eventLabel": /^Eurostar (Standard|Plus|Premier)$/,
  "noChanges": /^(0|null|undefined)$/,
  "sClassOutbound": /^Eurostar (Standard|Plus|Premier)$/,
  "sOutboundTime": "@PATTERNS.time",
  "sOutboundArrivalTime": "@PATTERNS.time",
  "sOutboundConnectionCode": "@PATTERNS.connectionCode", 
  "sOutboundConnectionOperator": /^(null|undefined)$/,
  "sTrainNumberOutbound": "@PATTERNS.trainNumber",
  "sTrainTarriffOutbound": "@PATTERNS.trainTariffOptional",
  "basket_value": "@PATTERNS.priceRange",
  "sTrainSaleTagsOutbound": "@PATTERNS.anyText",
  "basket_value_inpoints": "@PATTERNS.priceRange",
  "priceAdultOutbound": "@PATTERNS.priceRange",
  "priceChildOutbound": "@PATTERNS.priceRange",
  "priceYouthOutbound": "@PATTERNS.priceRange",
  "priceSeniorOutbound": "@PATTERNS.priceRange",
  "eventName": "InteractionEvent",
  "event": "TealiumLink"
}, 
{
  "eventAction": "Open Inbound Fare Details",
  "eventCategory": "Train Selection",
  "eventLabel": /^Eurostar (Standard|Plus|Premier)$/,
  "noChanges": /^(0|null|undefined)$/,
  "sClassInbound": "@PATTERNS.trainClass",
  "sInboundTime": "@PATTERNS.time",
  "sInboundArrivalTime": "@PATTERNS.time",
  "sInboundConnectionCode": "@PATTERNS.connectionCode", 
  "sInboundConnectionOperator": "@PATTERNS.connectionOperatorInbound",
  "sTrainNumberInbound": "@PATTERNS.trainNumberInbound",
  "sTrainTarriffInbound": "@PATTERNS.trainTariffOptional",
  "basket_value": "@PATTERNS.priceRange",
  "sTrainSaleTagsInbound": "@PATTERNS.anyText",
  "basket_value_inpoints": "@PATTERNS.priceRange",
  "priceAdultInbound": "@PATTERNS.priceRange",
  "priceChildInbound": "@PATTERNS.priceRange",
  "priceYouthInbound": "@PATTERNS.priceRange",
  "priceSeniorInbound": "@PATTERNS.priceRange",
  "eventName": "InteractionEvent",
  "event": "TealiumLink"
},
{
	eventCategory: "Train Selection",
	eventAction: /^Open (Out|In)bound Itinerary Details$/,
	sTrainNumberOutbound: "@PATTERNS.trainNumber",
	sOutboundTime: "@PATTERNS.time",
	sTrainTarriffOutbound: "@PATTERNS.trainTariffOptional",
	noChanges: "@PATTERNS.number",
	basket_value: "@PATTERNS.number",
	basket_value_inpoints: "@PATTERNS.number",
	eventName: "InteractionEvent",
	event: "TealiumLink"
},
{
  "eventAction": "Outbound",
  "eventCategory": "Date Picker",
  "eventLabel": /^(\+|\-)\d{1,20}\:(Next|Previous)$/,
  "sDateOutbound": "@PATTERNS.date",
  "basket_value": "@PATTERNS.priceRange",
  "basket_value_inpoints": "@PATTERNS.priceRange",
  "eventName": "InteractionEvent",
  "event": "TealiumLink"
},
	{
	eventAction: /^(In|Out)bound$/,
	eventCategory: "Date Picker",
	eventLabel: /^Chevron (Next|Previous)$/,
	eventName: "InteractionEvent",
	event: "TealiumLink"
},
{
  "eventAction": "Hotel Selection",
  "eventCategory": "Product tile",
  "hHotelDetails": /^.+\|\d+\|.+$/,
  "hotelId": ["@PATTERNS.number"],
  "hotelName": ["@PATTERNS.requiredText"],
  "hHotelPackagePromotion": ["@PATTERNS.number"],
  "hHotelPackageSavings": ["@PATTERNS.number"],
  "hHotelPriceAllPassengers": ["@PATTERNS.number"],
  "hHotelReviewCount": ["@PATTERNS.number"],
  "hHotelReviewScore": [/^\d+(\.\d+)?$/],
  "hHotelStarRating": ["@PATTERNS.hotelStarRating"],
  "eventName": "InteractionEvent",
  "event": "TealiumLink"
},
{
  eventAction: "Room selection",
  eventCategory: "Hotel room card",
  eventLabel: "Continue",
  currency: "@PATTERNS.currency",
  ecommerce_action: "add",
  basket_value: "@PATTERNS.priceDecimal",
  basket_value_inpoints: "@PATTERNS.number",
  products_count: "@PATTERNS.number",
  product_id: ["@PATTERNS.number"],
  product_name: ["@PATTERNS.requiredText"],
  product_quantity: [1],
  product_price: ["@PATTERNS.priceDecimal"],
  product_category: ["hotels"],
  product_variant: ["@PATTERNS.requiredText"],
  product_hotel_room_extra: ["@PATTERNS.requiredText"],
  product_cancellation_policy: [/^full|none$/],
  eventName: "InteractionEvent",
  event: "TealiumLink"
},
{
	eventCategory: "Hotel Upsell",
	eventAction: "Viewed",
	eventLabel: "Impression",
	eventNonInteraction: true,
	package_searchresults: "@PATTERNS.anyText",
	ecommerce_action: "product impressions",
	products_count: 5,
	product_id: ["@PATTERNS.number"],
        product_name: ["@PATTERNS.requiredText"],
	product_quantity: [1],
        product_price: ["@PATTERNS.priceDecimal"],
	product_price_inpoints:  ["@PATTERNS.priceDecimal"],
	product_brand: ["@PATTERNS.anyText"],
	product_category: [/^(hotels)$/],
	product_departure_date: ["@PATTERNS.date"],
	product_return_date: ["@PATTERNS.date"],
	product_hotel_origin_code: ["@PATTERNS.number"],
	product_hotel_destination_code: ["@PATTERNS.number"],
	product_hotel_occupancy: ["@PATTERNS.hotelOccupancy"],
	product_hotel_starrating: ["@PATTERNS.hotelStarRating"],
	product_hotel_review_count: ["@PATTERNS.number"],
	product_hotel_review_score: ["@PATTERNS.anyText"],
	product_hotel_promotion: ["@PATTERNS.anyText"],
	product_hotel_package_savings: ["@PATTERNS.anyText"],
	eventName: "ImpressionEvent",
	event: "TealiumLink"
},
{
	eventAction: "Click",
	eventCategory: "Attractions Carousel",
	eventLabel: "Arrows",
	eventName: "InteractionEvent",
	event: "TealiumLink"
},
{
eventCategory: "Insurance Selection",
eventAction: /^(Uns|S)elected Policy$/,
eventLabel: "@PATTERNS.insuranceType",
insuranceProviders: "Allianz",
insuranceType: "@PATTERNS.insuranceType",
insurancePrice: "@PATTERNS.priceDecimal",
basket_value: "@PATTERNS.priceDecimal",
eventName: "InteractionEvent",
event: "TealiumLink"
},
{
  "event": "TealiumLink",
  "eventName": "InteractionEvent", 
  "eventCategory": "Side Basket",
  "eventAction": "@PATTERNS.expandCollapseActions"
},
{
eventAction: "Edit",
eventLabel: /^(Out|In)bound Train$/,
eventCategory: "Side Basket",
eventName: "InteractionEvent",
event: "TealiumLink"
},
{
	eventAction: "Remove",
	eventLabel: "Insurance",
	eventCategory: "Side Basket",
	eventName: "InteractionEvent",
	event: "TealiumLink"
},	
{
eventAction: "@PATTERNS.loginActions",
currency: /^[A-Z]{3}$/,
funnel_name: "@PATTERNS.funnelName",
page_name: "Login",
page_category: "Checkout",
ld_version: "design-system",
eventCategory: "Login or Register",
eventLabel: /^(Login click|Login success|Login to Register|Check out as a guest)$/,
formName: /^(header|checkout|login|booking-magnet-header|booking-magnet-footer|eurostar-for-business)$/,
eventName: "InteractionEvent",
event: "TealiumLink"
},
{
	eventAction: "Forgotten your password",
	eventCategory: "Login or Register",
	formName: "header",
	eventName: "InteractionEvent",
	event: "TealiumLink"
},
{
	eventAction: "Reset password email",
	eventCategory: "Login or Register",
	eventLabel: "Reset password email",
	eventName: "InteractionEvent",
	event: "TealiumLink"
},
{
	eventAction: "Register",
	eventCategory: "Login or Register",
	eventLabel: "Register click",
	formName: "registration",
	eventName: "InteractionEvent",
	event: "TealiumLink"
},
{
	eventAction: "Register",
	eventCategory: "Login or Register",
	eventLabel: "Register success",
	formName: "registration",
	eventName: "InteractionEvent",
	event: "TealiumLink"
},
{
	eventAction: "Reset password email",
	eventCategory: "Login or Register",
	eventLabel: "Reset password email sent",
	eventName: "InteractionEvent",
	event: "TealiumLink"
},
{
  event: "TealiumLink",
  eventName: "InteractionEvent",
  eventCategory: "Passenger Details",
  eventAction: "Select A Passenger",
  eventLabel: "Existing Passenger"
},
{
  event: "TealiumLink",
  eventName: "InteractionEvent",
  eventCategory: "Passenger Details",
  eventAction: "Select A Passenger",
  eventLabel: "New Passenger"
},
{
	event: "TealiumLink",
	eventName: "InteractionEvent",
	eventCategory: "Passenger Details",
	eventAction: "Click",
	eventLabel: "Save New Passenger To Account:Check"
},
{
	event: "TealiumLink",
	eventName: "InteractionEvent",
	eventCategory: "Passenger Details",
	eventAction: "Click",
	eventLabel: "Save New Passenger To Account:Uncheck"
},
{
	eventAction: "Page Load",
	currency: "@PATTERNS.currency",
	funnel_name: "@PATTERNS.funnelName",
	page_name: "Checkout",
	page_category: "Checkout",
	ld_version: "design-system",
	eventCategory: "Page Timing",
	eventLabel: "Page Timing",
	eventNonInteraction: true,
	timings_cls: "@PATTERNS.anyText",
	timings_inp: "@PATTERNS.anyText",
	timings_lcp: "@PATTERNS.anyText",
	eventName: "SystemEvent",
	event: "TealiumLink"
},
  {
  event: "TealiumLink",
  eventName: "InteractionEvent",
  eventCategory: "Seating interaction",
  eventAction: /^"Seating changes (saved|discarded)"$/,
  eventLabel: /^"(inbound|outbound) (Changes made|No Changes made)"$/,
  ecommerce_action: "seat map",
  pnr: "@PATTERNS.pnr",
  product_id: ["7015400 - 8727100"],
  product_brand: ["ES"],
  product_category: ["trains"],
  product_variant: /^\["(inbound|outbound)"\]$/,
  product_departure_date: /^\["\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01])"\]$/,
  product_return_date: /^\["\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01])"\]$/,
  product_train_class: ["Standard"],
  product_train_route: ["london route"],
  product_train_origin_stationcode: ["8727100"],
  product_train_destination_stationcode: ["7015400"],
  product_train_number: ["9009"],
  product_train_fbccode: ["H19RSXARBG"],
  product_train_departuretime: ["07:43"],
  product_train_arrivaltime: ["11:02"],
  product_train_tickettype: ["PUB_STD_SF"],
  product_train_passenger_type: ["adult"],
  product_train_fare_name: ["through fare"],
  product_train_fare_type: ["ES_SR"]
},
        {"eventCategory":"Seating interaction","eventAction":"Seating changes saved","eventLabel":"outbound No Changes","ecommerce_action":"seat map","products_count":4,"product_status":["upcoming","upcoming"],"product_name":["8776500 - 8768600:adult","8727100 - 8400058:adult"],"product_id":["8776500 - 8768600","8727100 - 8400058"],"product_quantity":[2,2],"product_price":["182.60","230.00"],"product_brand":["SN","ER"],"product_category":["trains","trains"],"product_variant":["outbound","outbound"],"product_departure_date":["2025-03-28","2025-03-28"],"product_return_date":[],"product_train_class":["Standard Première","Eurostar Plus"],"product_train_route":["continent route","continent route"],"product_train_origin_stationcode":["8776500","8727100"],"product_train_destination_stationcode":["8768600","8400058"],"product_train_number":["6194","9339"],"product_train_fbccode":["SNCF1SFAD","TH01PSXASBEN"],"product_train_departuretime":["07:02","12:22"],"product_train_arrivaltime":["10:48","15:50"],"product_train_numberofconnections":[2,2],"product_train_connectioncode":["@PATTERNS.connectionCode"],"product_train_connectionoperator":["SNCF","Eurostar"],"product_train_tickettype":["SNCF1SF","RED_ESTAR_PUB_PLUS"],"product_train_passenger_type":["adult","adult"],"product_hotel_destination_code":[],"product_hotel_starrating":[],"product_hotel_origin_code":[],"product_hotel_occupancy":[],"product_hotel_review_count":[],"product_hotel_review_score":[],"product_hotel_room_extra":[],"product_hotel_promotion":[],"product_hotel_package_savings":[],"product_train_fare_name":["summated fare","summated fare"],"product_train_fare_type":["ER_SN","ER_SN"],"eventName":"InteractionEvent","event":"TealiumLink"},


{
	"eventCategory":"Train Upgrade",
	"eventAction":"Selected Outbound",
	"eventLabel":"Eurostar Standard > Eurostar Plus",
	"ecommerce_action":"add",
	"basket_value":"@PATTERNS.number",
	"basket_value_inpoints":"@PATTERNS.number",
	"pointsOrRegular":"@PATTERNS.bookingType",
	"products_count":"@PATTERNS.number",
	"product_name":[/^\d{7} - \d{7}(:adult)?$/], 
	"product_id":[/^\d{7} - \d{7}$/],
	"product_quantity":["@PATTERNS.number"],
	"product_price":["@PATTERNS.priceDecimal"],
	"product_price_inpoints":["@PATTERNS.number"],
	"product_brand":[/^[A-Z]{2}$/],
	"product_category":["trains"],
	"product_variant":["/inbound|outbound/"],
	"product_departure_date":["@PATTERNS.date"],
	"product_return_date":[null],
	"product_train_class": ["@PATTERNS.trainClass"],
  "product_train_route": ["@PATTERNS.trainRoute"],
	"product_train_origin_stationcode": ["@PATTERNS.stationCode"],
  "product_train_destination_stationcode": ["@PATTERNS.stationCode"],
  "product_train_number": ["@PATTERNS.trainNumber"],
	"product_train_fbccode": ["@PATTERNS.anyText"], 
  "product_train_departuretime": ["@PATTERNS.time"],
  "product_train_arrivaltime": ["@PATTERNS.time"],
	"product_train_numberofconnections": ["@PATTERNS.number"],
	"product_train_connectioncode":["@PATTERNS.connectionCode"],
	"product_train_connectionoperator": ["@PATTERNS.connectionOperator"],
  "product_train_tickettype": ["@PATTERNS.trainTicketType"],
	"product_train_passenger_type": ["adult"],
	"product_train_fare_name":[],
	"product_train_fare_type":[],
	"eventName":"InteractionEvent",
	"event":"TealiumLink"
},
{
	eventCategory: "Train Upgrade",
	eventAction: "Unselected Outbound",
	eventLabel: "Eurostar Standard > Eurostar Plus",
	upgradeRoute: "outbound",
	upgradeClass: "@PATTERNS.trainClass",
	upgradePrice: "@PATTERNS.priceDecimal",
	sTrainNumberOutbound: "@PATTERNS.trainNumber",
	sOutboundTime: "@PATTERNS.time",
	sClassOutbound: "@PATTERNS.trainClass",
	sTrainTarriffOutbound: /^[A-Z0-9]{11}$/,
	basket_value: "@PATTERNS.priceDecimalOptional",
	eventName: "InteractionEvent",
	event: "TealiumLink" 
},
{
	"eventAction":"Login",
	"currency":"@PATTERNS.currency",
	"funnel_name": "@PATTERNS.funnelName",
	"page_name":"Login",
	"page_category":"Checkout",
	"ld_version":"design-system",
	"eventCategory":"Login or Register",
	"eventLabel":"Check out as a guest",
	"formName":"checkout",
	"eventName":"InteractionEvent",
	"event":"TealiumLink"
},
        {"event":"TealiumView","page_category":"Bookings","isLoggedIn":"true","customer_hashedemail":"@PATTERNS.hashedEmail","customer_is_admin":"false","loyaltyTier":"Etoile","membershipID":"30838110000069353","membershipDetails":"Points: 1363811; Points to upgrade: N/A","pointsToSpend":1363811,"pointsToUpgrade":null,"subscriptionType":"premium-pass","subscriptionDuration":6,"subscriptionRemainingDuration":134,"mktOptions":"false","page_name":"Bookings/UpcomingBookings"},
        {"eventAction":"Click","eventCategory":"Bookings","eventLabel":"View Booking","eventName":"InteractionEvent","event":"TealiumLink"},
        {
            eventAction: "Click",
            currency: "@PATTERNS.currency",
            funnel_name: "@PATTERNS.funnelName",
            page_name: "Checkout",
            page_category: "Checkout",
            ld_version: "design-system",
            eventCategory: "Checkout Interaction",
            eventLabel: "Buy Now",
            eventName: "InteractionEvent",
            event: "TealiumLink"
        },
        {
            eventAction: "Form Submission",
            currency: "@PATTERNS.currency",
            funnel_name: "@PATTERNS.funnelName",
            page_name: "Checkout",
            page_category: "Checkout",
            ld_version: "design-system",
            eventCategory: "Checkout Interaction",
            paymentDetails: "@PATTERNS.paymentDetails",
            paymentCardType: "@PATTERNS.paymentCardType",
            eventName: "InteractionEvent",
            event: "TealiumLink"
        },
        {
            eventAction: "Select A Passenger",
            currency: "@PATTERNS.currency",
            funnel_name: "@PATTERNS.funnelName",
            page_name: "Checkout",
            page_category: "Checkout",
            ld_version: "design-system",
            eventCategory: "Booking Contact",
            eventLabel: "Existing Passenger",
            eventName: "InteractionEvent",
            event: "TealiumLink"
        },
        {
            eventAction: "Points payment unselected",
            currency: "@PATTERNS.currency",
            funnel_name: "@PATTERNS.funnelName",
            page_name: "Checkout",
            page_category: "Checkout",
            ld_version: "design-system",
            eventCategory: "Points usage",
            eventName: "InteractionEvent",
            event: "TealiumLink"
        },
        {
            event: "TealiumLink",
            eventName: "InteractionEvent",
            eventCategory: "Checkout Interaction",
            eventAction: "Payment Method Selection",
            paymentDetails: /^(Saved)?Card$/
        },
        {"eventAction":"@PATTERNS.fieldActions","currency":"@PATTERNS.currency","funnel_name":"Trains","page_name":"Checkout","page_category":"Checkout","ld_version":"design-system","eventCategory":"Passenger Details","eventLabel":"passengers.0.firstName","eventName":"InteractionEvent","event":"TealiumLink"},
        {"eventAction":"@PATTERNS.fieldActions","currency":"@PATTERNS.currency","funnel_name":"Trains","page_name":"Checkout","page_category":"Checkout","ld_version":"design-system","eventCategory":"Passenger Details","eventLabel":"passengers.0.lastName","eventName":"InteractionEvent","event":"TealiumLink"},
        {"eventAction":"@PATTERNS.fieldActions","currency":"@PATTERNS.currency","funnel_name":"Trains","page_name":"Checkout","page_category":"Checkout","ld_version":"design-system","eventCategory":"Passenger Details","eventLabel":"passengers.0.email","eventName":"InteractionEvent","event":"TealiumLink"},
        {"eventAction":"@PATTERNS.fieldActions","currency":"@PATTERNS.currency","funnel_name":"Trains","page_name":"Checkout","page_category":"Checkout","ld_version":"design-system","eventCategory":"Passenger Details","eventLabel":"passengers.0.mobile","eventName":"InteractionEvent","event":"TealiumLink"},
        {
		"eventAction":"Click",
		"currency":"@PATTERNS.currency",
		"funnel_name":/^(Trains|Hotels|Packages)$/,
		"page_name":"Checkout",
		"page_category":"Checkout",
		"ld_version":"design-system",
		"eventCategory":"Newsletter",
		"eventLabel":"Opt-Out",
		"mktOptions":"false",
		"eventName":"InteractionEvent",
		"event":"TealiumLink"
	},
        {"eventCategory":"Passenger detail","eventAction":"Contact details","eventLabel":"Save contact details:button","eventName":"InteractionEvent","event":"TealiumLink"},
        {
            eventAction: "Validation Error",
            eventCategory: "Error",
            eventLabel: "@PATTERNS.anyText",
            errorMessage: "@PATTERNS.anyText",
            eventName: "ErrorEvent",
            event: "TealiumLink"
        },
	{
		eventAction: "Expand",
		eventCategory: "Passenger Details",
		eventLabel: "Membership number accordion",
		eventName: "InteractionEvent",
		event: "TealiumLink"
	},
        {
            event: 'TealiumLink',
            eventName: 'InteractionEvent',
            eventCategory: 'Optional question',
            eventAction: 'Reason for travel - Selection',
            eventLabel: ["reasons for this travel : business", "reasons for this travel : holiday", "reasons for this travel : visiting family or friends"]
        },
        {"currency":"@PATTERNS.currency","funnel_name":"Trains","page_category":"Checkout","ld_version":"design-system","event":"TealiumView","activityType":"train exchange","isLoggedIn":false,"customer_hashedemail":"@PATTERNS.hashedEmail","customer_is_admin":null,"businessID":null,"loyaltyTier":null,"membershipID":null,"membershipDetails":null,"pointsToSpend":null,"pointsToUpgrade":null,"directOrConnection":"direct","sJourneyType":"One way","sFromCode":"7015400","sFromName":"London St Pancras Int'l","sToCode":"8727100","sToName":"Paris Gare du Nord","sDateOutbound":"2024-10-23","sDateInbound":"","sTravelHorizon":0,"sTravelDuration":null,"sPaxTotal":1,"sPaxAdult":1,"sPaxChildren":0,"sPaxInfants":0,"sPaxSenior":0,"sPaxYouth":0,"sPaxCompanion":0,"basket_value_inpoints":0,"pointsOrRegular":"regular booking","promoBooking":"","ecommerce_action":"checkout","payment_methods":"Card|GooglePay|Invoice|PayPal","club_eurostar_discount":"none","basket_value":270,"products_count":1,"product_brand":["ES"],"product_id":["7015400 - 8727100"],"product_category":["trains"],"product_name":["7015400 - 8727100:adult"],"product_price":["270.00"],"product_price_inpoints":["0"],"product_quantity":[1],"product_train_numberofconnections":[1],"product_departure_date":["2024-10-23"],"product_train_departuretime":["18:01"],"product_train_fbccode":["H01PSXASBGX"],"product_train_number":["9046"],"product_variant":["outbound"],"product_hotel_origin_code":[],"product_hotel_destination_code":[],"product_hotel_occupancy":[],"product_hotel_starrating":[],"product_hotel_review_count":[],"product_hotel_review_score":[],"product_hotel_room_extra":[],"product_return_date":[],"product_train_class":["Standard Premier"],"product_train_route":["london route"],"product_train_origin_stationcode":["7015400"],"product_train_destination_stationcode":["8727100"],"product_train_arrivaltime":["21:28"],"product_train_tickettype":["ES_PUB_SP"],"product_train_connectionoperator":[null],"product_train_passenger_type":["adult"],"product_train_fare_name":[],"product_train_fare_type":[],"page_name":"Checkout"},
	{
		eventAction: "Points payment selected",
		currency: "@PATTERNS.currency",
		funnel_name: "@PATTERNS.funnelName",
		page_name: "Checkout",
		page_category: "Checkout",
		ld_version: "design-system",
		eventCategory: "Points usage",
		eventLabel: /^.{1,3}$/,
		eventName: "InteractionEvent",
		event: "TealiumLink"
	},
        {
            event: "TealiumLink",
            eventName: "InteractionEvent",
            eventCategory: "Booking Contact",
            eventAction: "Select A Passenger",
            eventLabel: "Existing Passenger"
        },
        {
            "event":"TealiumView",
            "page_category":"Overview",
            "isLoggedIn":"true",
            "customer_hashedemail":"@PATTERNS.hashedEmail",
            "customer_is_admin":"false",
            "loyaltyTier":"Carte Blanche",
            "membershipID": "@PATTERNS.membershipID",
            "membershipDetails":"Points: 801; Points to upgrade: 2859",
            "pointsToSpend":"@PATTERNS.number",
            "pointsToUpgrade":"@PATTERNS.number",
            "subscriptionType":"frequent-pass",
            "subscriptionDuration":"@PATTERNS.number",
            "subscriptionRemainingDuration":"@PATTERNS.number",
            "mktOptions":"false",
            "page_name":"Overview"
        },
            {
        currency: "@PATTERNS.currency",
        funnel_name: "@PATTERNS.funnelName",
        page_category: "Checkout",
        ld_version: "design-system",
        event: "TealiumView",
        activityType: "train exchange",
        isLoggedIn: "@PATTERNS.boolean",
        customer_hashedemail: "@PATTERNS.hashedEmail",
        customer_is_admin: "@PATTERNS.booleanOptional",
        businessID: null,
        loyaltyTier: /^(Carte Blanche|Silver|Gold|null)$/,
        membershipID: "@PATTERNS.membershipID",
        membershipDetails: "@PATTERNS.membershipDetails",
        pointsToSpend: "@PATTERNS.number",
        pointsToUpgrade: "@PATTERNS.number",
        directOrConnection: "@PATTERNS.connectionType",
        sJourneyType: "@PATTERNS.journeyType",
        sFromCode: "@PATTERNS.stationCode",
        sFromName: "@PATTERNS.requiredText",
        sToCode: "@PATTERNS.stationCode",
        sToName: "@PATTERNS.requiredText",
        sDateOutbound: "@PATTERNS.date",
        sDateInbound: /^$|^\d{4}-\d{2}-\d{2}$/,
        sTravelHorizon: "@PATTERNS.number",
        sTravelDuration: null,
        sPaxTotal: "@PATTERNS.number",
        sPaxAdult: "@PATTERNS.number",
        sPaxChildren: "@PATTERNS.number",
        sPaxInfants: "@PATTERNS.number",
        sPaxSenior: "@PATTERNS.number",
        sPaxYouth: "@PATTERNS.number",
        sPaxCompanion: "@PATTERNS.numberOptional",
        basket_value_inpoints: "@PATTERNS.number",
        pointsOrRegular: "@PATTERNS.bookingType",
        promoBooking: "@PATTERNS.anyText",
        ecommerce_action: "checkout",
        payment_methods: "@PATTERNS.paymentMethods",
        club_eurostar_discount: /(none|member)/,
        basket_value: "@PATTERNS.priceDecimalOptional",
        products_count: "@PATTERNS.number",
        product_brand: [/^(ES|[A-Z]+)$/],
        product_id: [/^\d{7} - \d{7}$/],
        product_category: ["trains"],
        product_name: [/^\d{7} - \d{7}:adult$/],
        product_price: ["@PATTERNS.priceDecimal"],
        product_price_inpoints: ["@PATTERNS.number"],
        product_quantity: ["@PATTERNS.number"],
        product_train_numberofconnections: ["@PATTERNS.number"],
        product_departure_date: ["@PATTERNS.date"],
        product_train_departuretime: ["@PATTERNS.time"],
        product_train_fbccode: ["@PATTERNS.requiredText"],
        product_train_number: ["@PATTERNS.number"],
        product_variant: ["outbound"],
        product_hotel_origin_code: [],
        product_hotel_destination_code: [],
        product_hotel_occupancy: [],
        product_hotel_starrating: [],
        product_hotel_review_count: [],
        product_hotel_review_score: [],
        product_hotel_room_extra: [],
        product_return_date: [],
        product_train_class: ["Eurostar Plus"],
        product_train_route: ["london route"],
        product_train_origin_stationcode: ["@PATTERNS.stationCode"],
        product_train_destination_stationcode: ["@PATTERNS.stationCode"],
        product_train_arrivaltime: ["@PATTERNS.time"],
        product_train_tickettype: ["ESTAR_PUB_PLUS"],
        product_train_connectionoperator: [null],
        product_train_passenger_type: ["adult"],
        product_train_fare_name: [],
        product_train_fare_type: [],
        page_name: "Checkout"
    },
{
	eventAction: "Register",
	currency: "@PATTERNS.currency",
	funnel_name: /^(Trains|Packages|Hotels)$/,
	page_name: "BookingConfirmation",
	page_category: "BookingConfirmation",
	eventCategory: "Sign Up Now",
	eventLabel: "Register click",
	formName: "checkout",
	eventName: "InteractionEvent",
	event: "TealiumLink"
},
	{
	eventAction: "Validation Error",
	currency: "@PATTERNS.currency",
	funnel_name: /^(Trains|Packages|Hotels)$/,
	page_name: "BookingConfirmation",
	page_category: "BookingConfirmation",
	eventCategory: "Error",
	eventLabel: "@PATTERNS.anyText",
	errorMessage: "@PATTERNS.anyText",
	formName: "checkout",
	eventName: "ErrorEvent",
	event: "TealiumLink"
},
{
	eventAction: "Verification",
	currency: "@PATTERNS.currency",
	funnel_name: /^(Trains|Packages|Hotels)$/,
	page_name: "BookingConfirmation",
	page_category: "BookingConfirmation",
	eventCategory: "Overlay",
	eventLabel: "Verify Click",
	formName: "checkout",
	eventName: "InteractionEvent",
	event: "TealiumLink"
},
{
	eventAction: "Verification",
	currency: "@PATTERNS.currency",
	funnel_name: /^(Trains|Packages|Hotels)$/,
	page_name: "BookingConfirmation",
	page_category: "BookingConfirmation",
	eventCategory: "Overlay",
	eventLabel: "Impressions",
	formName: "checkout",
	eventName: "InteractionEvent",
	event: "TealiumLink"
},	
{
	eventAction: "Verification",
	currency: "@PATTERNS.currency",
	funnel_name: /^(Trains|Packages|Hotels)$/,
	page_name: "BookingConfirmation",
	page_category: "BookingConfirmation",
	eventCategory: "Overlay",
	eventLabel: "Verify Success",
	formName: "checkout",
	eventName: "InteractionEvent",
	event: "TealiumLink"
},
{
	eventAction: "Register",
	currency: "@PATTERNS.currency",
	funnel_name: /^(Trains|Packages|Hotels)$/,
	page_name: "BookingConfirmation",
	page_category: "BookingConfirmation",
	eventCategory: "Sign Up Now",
	eventLabel: "Register success",
	formName: "checkout",
	eventName: "InteractionEvent",
	event: "TealiumLink"
},
{
	eventCategory: "Exchange journey leg selection",
	eventAction: "Add",
	eventLabel: /^(Inbound|Outbound|Outbound\|Inbound)$/,
	eventName: "InteractionEvent",
	event: "TealiumLink"
},
{
	eventCategory: "MYB interaction",
	eventAction: "Click",
	eventLabel: /^(Upgrade Booking|Exchange Booking|Get Tickets|Cancel Package Booking")$/,
	interactionSection: /^(action menu|get tickets card)$/,
	eventName: "InteractionEvent",
	event: "TealiumLink"
},
	{
	eventAction: "Enter A Booking Reference",
	eventCategory: "Bookings",
	eventLabel: /^(Search|Booking Added)$/,
	eventName: "InteractionEvent",
	event: "TealiumLink"
},
  {
    "event": "TealiumLink",
    "eventName": "InteractionEvent",
    "eventCategory": "Eurostar Chatbot",
    "eventAction": "Start Conversation",
    "conversationId": "@PATTERNS.conversationId"
  },
{
	eventAction: "Click",
	eventCategory: "Lowest Fare Finder",
	eventLabel: /^(Select Destination|Select Outbound Month|Select Journey Type|Select Outbound Journey|Select Inbound Journey|Get Train Times)$/,
	currency: "@PATTERNS.currency",
	sFromCode: "@PATTERNS.stationCode",
        sFromName: "@PATTERNS.requiredText",
        sToCode: "@PATTERNS.stationCode",
        sToName: "@PATTERNS.requiredText",
	sJourneyType: "@PATTERNS.journeyType",
	sPaxTotal: "@PATTERNS.number",
        sPaxAdult: "@PATTERNS.number",
        sPaxChildren: "@PATTERNS.number",
        sPaxInfants: "@PATTERNS.number",
        sPaxSenior: "@PATTERNS.number",
        sPaxYouth: "@PATTERNS.number",
        sPaxCompanion: "@PATTERNS.companionCount",
	sDateOutboundBookingMonth: /^\d{4}_\S{3}$/,
	sDateInboundBookingMonth: /^\d{4}_\S{3}$/,
	sDateOutbound: /^null|\d{4}-\d{2}-\d{2}$/,
        sDateInbound: /^null|\d{4}-\d{2}-\d{2}$/,
	sOutboundLowestFare: "@PATTERNS.number",
	sInboundLowestFare: "@PATTERNS.number",
	priceAdultOutbound: /^(null|0|[1-9][0-9]{0,3}|10000)(\.[0-9]{1,2})?$/,
	priceAdultInbound: /^(null|0|[1-9][0-9]{0,3}|10000)(\.[0-9]{1,2})?$/,
	pointsOrRegular: "@PATTERNS.bookingType",
	eventName: "InteractionEvent",
	event: "TealiumLink"
},	
{
  event: "TealiumLink",
  eventName: "InteractionEvent",
  eventCategory: "EurostarForBusiness",
  eventAction: "Your Business",
  eventLabel: "AddBillieToCheckout:Click"
},
{
  event: "TealiumLink",
  eventName: "InteractionEvent",
  eventCategory: "EurostarForBusiness",
  eventAction: "Your Business",
  eventLabel: "AddBillieToCheckout:Success"
},
{
  event: "TealiumLink",
  eventName: "InteractionEvent",
  eventCategory: "EurostarForBusiness",
  eventAction: "Your Business",
  eventLabel: "DifferentEmailSave:Click"
},	
{
  event: "TealiumLink",
  eventName: "InteractionEvent",
  eventCategory: "EurostarForBusiness",
  eventAction: "Your Business",
  eventLabel: "DifferentEmailSave:Success"
}	
];
